### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fivetanley** [rwdaigle/metrix#17]
Hello there!

Thanks for writing and maintaining metrix. It looks like a great library! I would love to use and contribute to it, but without a license, I'm unable to get permission to use/contribute from my employer.

**Comment by rwdaigle** [comment]
Hi @fivetanley! Thanks for this request. I am somewhat partial to the MIT license - do you have any strong opinions on which license?

**Comment by fivetanley** [comment]
MIT is pretty friendly to most needs in general and used by a lot of elixir projects. This is not legal advice but Rails, Phoenix, and many projects use MIT and it's pretty amenable to businesses as well.
