### ISSUE TITLE
Logger.info instead of IO.puts

### ISSUE THREAD

**Issue by sergiobuj** [rwdaigle/metrix#5]
Hi,

I noted the Logger/log level integration in the todo list. I am currently getting my metrics when running tests and is adding unnecessary noise.

This diff works great for me but wanted to know your original idea for the level integration.

``` diff
diff --git a/lib/metrix.ex b/lib/metrix.ex
index 8be6632..ed8179f 100644
--- a/lib/metrix.ex
+++ b/lib/metrix.ex
@@ -70,5 +70,5 @@ defmodule Metrix do

   defp add(dict, key, value), do: dict |> Dict.put(key, value)

-  defp write(output), do: output |> IO.puts
+  defp write(output), do: output |> Logger.info
 end
```

**Comment by rwdaigle** [comment]
Hi @sergiobuj, thanks for this!

So my initial thought is that I'd like the output target to be configurable. In production I actually do want it to go to STDOUT, but in test I might want it silenced or to go to a file.

What are your thoughts on how that would be handled?

**Comment by guilleiguaran** [comment]
@sergiobuj @rwdaigle I think an alternative is using `Logger.log` and then the user can take care of the logging level and backend (file, console, etc) using logger configuration.

In default config.exs we can have something like:

``` elixir
config :metrix,
  log_level: :info
```

And of course this can be changed per-env in `test.exs`, `dev.exs` and `prod.exs` files.

Then in the code we can have something like this:

``` elixir
defp write(output) do
  level = Application.get_env(:metrix, :log_level, :info) # or maybe we should fallback to `:debug` by default?
  Logger.log(level, output)
end
```

What do you think?

**Comment by rwdaigle** [comment]
@guilleiguaran this might not be idiomatic Elixir, but what about a solution that lets the user pass in a function that does the writing?

``` elixir
config :metrix,
  write: fn output -> Logger.log(:info, output) end
```

Then in Metrix:

``` elixir
defp write(output) do
  print = Application.get_env(:metrix, :write) || fn output -> IO.puts output end
  print(output)
end
```

Seems like this approach provides a lot of flexibility. Are there any downsides?

**Comment by guilleiguaran** [comment]
@rwdaigle I'm not sure if it's idiomatic Elixir neither but one problem I see with that approach is that Erlang Releases tools for Elixir (relex, exrm, ...) will fail trying to generate a standard Erlang `sys.config` from the `config.exs` because the anonymous function can't be directly translated to an Erlang term.

**Comment by rwdaigle** [comment]
> one problem I see with that approach is that Erlang Releases tools for Elixir (relex, exrm, ...) will fail trying to generate a standard Erlang sys.config from the config.exs because the anonymous function can't be directly translated to an Erlang term

I would have never thought of that, thanks @guilleiguaran!

So it definitely feels like using the `Logger` is the right approach here. There are just [too many benefits](http://elixir-lang.org/docs/stable/logger/Logger.html) like buffering, back-pressure, configuration etc.., to not use it. Also, the Logger defaults to using `:console` (STDOUT).

@sergiobuj if you want to put a PR together using `Logger` and @guilleiguaran's log-level config idea I'd be happy to pull it in? Let me know if that's something you want to do!
